### ISSUE TITLE
请问大神为什么要有start:pre这个命令

### ISSUE THREAD

**Issue by mike8625** [GuoYongfeng/webpack-dev-boilerplate#18]
我看其他人的git里面就直接npm start了. 为什么您这个会有一个start pre啊? 能否加载到start里面 先执行一个pre再运行原来的start?

**Comment by superNever** [comment]
不能，如果那样就会每次都进行pre处理，我们的原意是预处理的文件是几乎很少变动的，所以只进行一次预处理就可以了

**Comment by mike8625** [comment]
好的, 十分感谢
