### ISSUE TITLE
关于HtmlWebpackPlugin的问题

### ISSUE THREAD

**Issue by qq645381995** [GuoYongfeng/webpack-dev-boilerplate#2]
我看你的代码，可以在npm run dev 下面生成html  但是js和  index.html在一级，我用在我的项目中也可以，但是我想把js资源文件放在assets下面 index.html放在根目录下面，但是我build的时候可以，但是运行的时候就不可以，路径问题原因吧，我不知道怎么改，
我的  output 的 publicPath：‘/assets/’
        devServer的 publicPath：‘/assets/’
这个不是写的 ‘/’  所以要在 HtmlWebpackPlugin的filename修改，但是不知道要改成什么路径！

**Comment by GuoYongfeng** [comment]
可以配置`HtmlWebpackPlugin`这个插件的path

**Comment by qq645381995** [comment]
都多久了 反正能用了 以后懂的时候再说吧！
